// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismicT from "@prismicio/types";
import type * as prismic from "@prismicio/client";

type Simplify<T> = {
  [KeyType in keyof T]: T[KeyType];
};
/** Content for Event documents */
interface EventDocumentData {
  /**
   * Name field in *Event*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: event.name
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
   *
   */
  name: prismicT.KeyTextField;
  /**
   * Logo field in *Event*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: event.logo
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/core-concepts/image
   *
   */
  logo: prismicT.ImageField<never>;
  /**
   * Background field in *Event*
   *
   * - **Field Type**: Link to Media
   * - **Placeholder**: *None*
   * - **API ID Path**: event.background
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/core-concepts/link-content-relationship
   *
   */
  background: prismicT.LinkToMediaField;
  /**
   * Start Date field in *Event*
   *
   * - **Field Type**: Date
   * - **Placeholder**: *None*
   * - **API ID Path**: event.start
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/core-concepts/date
   *
   */
  start: prismicT.DateField;
  /**
   * End Date field in *Event*
   *
   * - **Field Type**: Date
   * - **Placeholder**: *None*
   * - **API ID Path**: event.end
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/core-concepts/date
   *
   */
  end: prismicT.DateField;
  /**
   * Slice Zone field in *Event*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: event.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/core-concepts/slices
   *
   */
  slices: prismicT.SliceZone<EventDocumentDataSlicesSlice>;
}
/**
 * Slice for *Event → Slice Zone*
 *
 */
type EventDocumentDataSlicesSlice =
  | CarouselSlice
  | GallerySlice
  | SponsorsSlice
  | ContentSlice
  | FormSlice;
/**
 * Event document from Prismic
 *
 * - **API ID**: `event`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/core-concepts/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type EventDocument<Lang extends string = string> =
  prismicT.PrismicDocumentWithUID<Simplify<EventDocumentData>, "event", Lang>;
/** Content for Navigation documents */
interface NavigationDocumentData {
  /**
   * Links field in *Navigation*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: navigation.links[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/core-concepts/group
   *
   */
  links: prismicT.GroupField<Simplify<NavigationDocumentDataLinksItem>>;
  /**
   * Slice Zone field in *Navigation*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: navigation.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/core-concepts/slices
   *
   */
  slices: prismicT.SliceZone<NavigationDocumentDataSlicesSlice>;
}
/**
 * Item in Navigation → Links
 *
 */
export interface NavigationDocumentDataLinksItem {
  /**
   * Label field in *Navigation → Links*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: navigation.links[].label
   * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
   *
   */
  label: prismicT.KeyTextField;
  /**
   * Link field in *Navigation → Links*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: navigation.links[].link
   * - **Documentation**: https://prismic.io/docs/core-concepts/link-content-relationship
   *
   */
  link: prismicT.LinkField;
}
/**
 * Slice for *Navigation → Slice Zone*
 *
 */
type NavigationDocumentDataSlicesSlice = never;
/**
 * Navigation document from Prismic
 *
 * - **API ID**: `navigation`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/core-concepts/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type NavigationDocument<Lang extends string = string> =
  prismicT.PrismicDocumentWithoutUID<
    Simplify<NavigationDocumentData>,
    "navigation",
    Lang
  >;
/** Content for Page documents */
interface PageDocumentData {
  /**
   * Slice Zone field in *Page*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: page.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/core-concepts/slices
   *
   */
  slices: prismicT.SliceZone<PageDocumentDataSlicesSlice>;
  /**
   * Meta Title field in *Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: page.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
   *
   */
  meta_title: prismicT.KeyTextField;
  /**
   * Meta Description field in *Page*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: page.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
   *
   */
  meta_description: prismicT.RichTextField;
  /**
   * Meta Image field in *Page*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: page.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/core-concepts/image
   *
   */
  meta_image: prismicT.ImageField<never>;
}
/**
 * Slice for *Page → Slice Zone*
 *
 */
type PageDocumentDataSlicesSlice =
  | PageHeaderSlice
  | TextHeaderSlice
  | ContentSlice
  | CarouselSlice
  | FormSlice
  | GallerySlice
  | SponsorsSlice
  | EventsSlice;
/**
 * Page document from Prismic
 *
 * - **API ID**: `page`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/core-concepts/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type PageDocument<Lang extends string = string> =
  prismicT.PrismicDocumentWithUID<Simplify<PageDocumentData>, "page", Lang>;
export type AllDocumentTypes =
  | EventDocument
  | NavigationDocument
  | PageDocument;
/**
 * Primary content in Carousel → Primary
 *
 */
interface CarouselSliceDefaultPrimary {
  /**
   * Label field in *Carousel → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: carousel.primary.section
   * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
   *
   */
  section: prismicT.KeyTextField;
  /**
   * Publish field in *Carousel → Primary*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: carousel.primary.hide
   * - **Documentation**: https://prismic.io/docs/core-concepts/boolean
   *
   */
  hide: prismicT.BooleanField;
  /**
   * Header field in *Carousel → Primary*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: carousel.primary.noHeader
   * - **Documentation**: https://prismic.io/docs/core-concepts/boolean
   *
   */
  noHeader: prismicT.BooleanField;
}
/**
 * Item in Carousel → Items
 *
 */
export interface CarouselSliceDefaultItem {
  /**
   * Media field in *Carousel → Items*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: carousel.items[].media
   * - **Documentation**: https://prismic.io/docs/core-concepts/link-content-relationship
   *
   */
  media: prismicT.LinkField;
  /**
   * Title field in *Carousel → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: carousel.items[].title
   * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
   *
   */
  title: prismicT.KeyTextField;
  /**
   * Subtitle field in *Carousel → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: carousel.items[].subtitle
   * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
   *
   */
  subtitle: prismicT.KeyTextField;
  /**
   * Body field in *Carousel → Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: carousel.items[].body
   * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
   *
   */
  body: prismicT.RichTextField;
  /**
   * Link field in *Carousel → Items*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: carousel.items[].link
   * - **Documentation**: https://prismic.io/docs/core-concepts/link-content-relationship
   *
   */
  link: prismicT.LinkField;
}
/**
 * Default variation for Carousel Slice
 *
 * - **API ID**: `default`
 * - **Description**: `Carousel`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type CarouselSliceDefault = prismicT.SharedSliceVariation<
  "default",
  Simplify<CarouselSliceDefaultPrimary>,
  Simplify<CarouselSliceDefaultItem>
>;
/**
 * Slice variation for *Carousel*
 *
 */
type CarouselSliceVariation = CarouselSliceDefault;
/**
 * Carousel Shared Slice
 *
 * - **API ID**: `carousel`
 * - **Description**: `Carousel`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type CarouselSlice = prismicT.SharedSlice<
  "carousel",
  CarouselSliceVariation
>;
/**
 * Primary content in Content → Primary
 *
 */
interface ContentSliceDefaultPrimary {
  /**
   * Label field in *Content → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: content.primary.section
   * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
   *
   */
  section: prismicT.KeyTextField;
  /**
   * Publish field in *Content → Primary*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: content.primary.hide
   * - **Documentation**: https://prismic.io/docs/core-concepts/boolean
   *
   */
  hide: prismicT.BooleanField;
}
/**
 * Item in Content → Items
 *
 */
export interface ContentSliceDefaultItem {
  /**
   * Text field in *Content → Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: content.items[].text
   * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
   *
   */
  text: prismicT.RichTextField;
  /**
   * Media field in *Content → Items*
   *
   * - **Field Type**: Link to Media
   * - **Placeholder**: *None*
   * - **API ID Path**: content.items[].media
   * - **Documentation**: https://prismic.io/docs/core-concepts/link-content-relationship
   *
   */
  media: prismicT.LinkToMediaField;
}
/**
 * Default variation for Content Slice
 *
 * - **API ID**: `default`
 * - **Description**: `Default`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type ContentSliceDefault = prismicT.SharedSliceVariation<
  "default",
  Simplify<ContentSliceDefaultPrimary>,
  Simplify<ContentSliceDefaultItem>
>;
/**
 * Slice variation for *Content*
 *
 */
type ContentSliceVariation = ContentSliceDefault;
/**
 * Content Shared Slice
 *
 * - **API ID**: `content`
 * - **Description**: `Content`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type ContentSlice = prismicT.SharedSlice<
  "content",
  ContentSliceVariation
>;
/**
 * Primary content in Events → Primary
 *
 */
interface EventsSliceDefaultPrimary {
  /**
   * Label field in *Events → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: events.primary.section
   * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
   *
   */
  section: prismicT.KeyTextField;
  /**
   * Publish field in *Events → Primary*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: events.primary.hide
   * - **Documentation**: https://prismic.io/docs/core-concepts/boolean
   *
   */
  hide: prismicT.BooleanField;
  /**
   * Display Type field in *Events → Primary*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: events.primary.carousel
   * - **Documentation**: https://prismic.io/docs/core-concepts/boolean
   *
   */
  carousel: prismicT.BooleanField;
}
/**
 * Item in Events → Items
 *
 */
export interface EventsSliceDefaultItem {
  /**
   * Event Picker field in *Events → Items*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: *None*
   * - **API ID Path**: events.items[].event
   * - **Documentation**: https://prismic.io/docs/core-concepts/link-content-relationship
   *
   */
  event: prismicT.RelationField<"event">;
}
/**
 * Default variation for Events Slice
 *
 * - **API ID**: `default`
 * - **Description**: `Events`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type EventsSliceDefault = prismicT.SharedSliceVariation<
  "default",
  Simplify<EventsSliceDefaultPrimary>,
  Simplify<EventsSliceDefaultItem>
>;
/**
 * Slice variation for *Events*
 *
 */
type EventsSliceVariation = EventsSliceDefault;
/**
 * Events Shared Slice
 *
 * - **API ID**: `events`
 * - **Description**: `Events Carousel`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type EventsSlice = prismicT.SharedSlice<"events", EventsSliceVariation>;
/**
 * Primary content in Form → Primary
 *
 */
interface FormSliceDefaultPrimary {
  /**
   * Label field in *Form → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: form.primary.section
   * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
   *
   */
  section: prismicT.KeyTextField;
  /**
   * Publish field in *Form → Primary*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: form.primary.hide
   * - **Documentation**: https://prismic.io/docs/core-concepts/boolean
   *
   */
  hide: prismicT.BooleanField;
  /**
   * Header field in *Form → Primary*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: form.primary.noHeader
   * - **Documentation**: https://prismic.io/docs/core-concepts/boolean
   *
   */
  noHeader: prismicT.BooleanField;
  /**
   * Airtable Link field in *Form → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: form.primary.airtable
   * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
   *
   */
  airtable: prismicT.KeyTextField;
  /**
   * Description field in *Form → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: form.primary.description
   * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
   *
   */
  description: prismicT.RichTextField;
}
/**
 * Default variation for Form Slice
 *
 * - **API ID**: `default`
 * - **Description**: `Default`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type FormSliceDefault = prismicT.SharedSliceVariation<
  "default",
  Simplify<FormSliceDefaultPrimary>,
  never
>;
/**
 * Slice variation for *Form*
 *
 */
type FormSliceVariation = FormSliceDefault;
/**
 * Form Shared Slice
 *
 * - **API ID**: `form`
 * - **Description**: `Form`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type FormSlice = prismicT.SharedSlice<"form", FormSliceVariation>;
/**
 * Primary content in Gallery → Primary
 *
 */
interface GallerySliceDefaultPrimary {
  /**
   * Label field in *Gallery → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: gallery.primary.section
   * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
   *
   */
  section: prismicT.KeyTextField;
  /**
   * Publish field in *Gallery → Primary*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: gallery.primary.hide
   * - **Documentation**: https://prismic.io/docs/core-concepts/boolean
   *
   */
  hide: prismicT.BooleanField;
}
/**
 * Item in Gallery → Items
 *
 */
export interface GallerySliceDefaultItem {
  /**
   * Media field in *Gallery → Items*
   *
   * - **Field Type**: Link to Media
   * - **Placeholder**: *None*
   * - **API ID Path**: gallery.items[].media
   * - **Documentation**: https://prismic.io/docs/core-concepts/link-content-relationship
   *
   */
  media: prismicT.LinkToMediaField;
  /**
   * Description field in *Gallery → Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: gallery.items[].description
   * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
   *
   */
  description: prismicT.RichTextField;
}
/**
 * Default variation for Gallery Slice
 *
 * - **API ID**: `default`
 * - **Description**: `Default`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type GallerySliceDefault = prismicT.SharedSliceVariation<
  "default",
  Simplify<GallerySliceDefaultPrimary>,
  Simplify<GallerySliceDefaultItem>
>;
/**
 * Slice variation for *Gallery*
 *
 */
type GallerySliceVariation = GallerySliceDefault;
/**
 * Gallery Shared Slice
 *
 * - **API ID**: `gallery`
 * - **Description**: `Gallery`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type GallerySlice = prismicT.SharedSlice<
  "gallery",
  GallerySliceVariation
>;
/**
 * Primary content in PageHeader → Primary
 *
 */
interface PageHeaderSliceDefaultPrimary {
  /**
   * Publish field in *PageHeader → Primary*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: page_header.primary.hide
   * - **Documentation**: https://prismic.io/docs/core-concepts/boolean
   *
   */
  hide: prismicT.BooleanField;
  /**
   * Title field in *PageHeader → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: page_header.primary.title
   * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
   *
   */
  title: prismicT.RichTextField;
  /**
   * Background field in *PageHeader → Primary*
   *
   * - **Field Type**: Link to Media
   * - **Placeholder**: *None*
   * - **API ID Path**: page_header.primary.background
   * - **Documentation**: https://prismic.io/docs/core-concepts/link-content-relationship
   *
   */
  background: prismicT.LinkToMediaField;
}
/**
 * Default variation for PageHeader Slice
 *
 * - **API ID**: `default`
 * - **Description**: `Default`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type PageHeaderSliceDefault = prismicT.SharedSliceVariation<
  "default",
  Simplify<PageHeaderSliceDefaultPrimary>,
  never
>;
/**
 * Slice variation for *PageHeader*
 *
 */
type PageHeaderSliceVariation = PageHeaderSliceDefault;
/**
 * PageHeader Shared Slice
 *
 * - **API ID**: `page_header`
 * - **Description**: `PageHeader`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type PageHeaderSlice = prismicT.SharedSlice<
  "page_header",
  PageHeaderSliceVariation
>;
/**
 * Primary content in Sponsors → Primary
 *
 */
interface SponsorsSliceDefaultPrimary {
  /**
   * Label field in *Sponsors → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: sponsors.primary.section
   * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
   *
   */
  section: prismicT.KeyTextField;
  /**
   * Publish field in *Sponsors → Primary*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: sponsors.primary.hide
   * - **Documentation**: https://prismic.io/docs/core-concepts/boolean
   *
   */
  hide: prismicT.BooleanField;
  /**
   * Header field in *Sponsors → Primary*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: sponsors.primary.noHeader
   * - **Documentation**: https://prismic.io/docs/core-concepts/boolean
   *
   */
  noHeader: prismicT.BooleanField;
}
/**
 * Item in Sponsors → Items
 *
 */
export interface SponsorsSliceDefaultItem {
  /**
   * Logo field in *Sponsors → Items*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: sponsors.items[].logo
   * - **Documentation**: https://prismic.io/docs/core-concepts/image
   *
   */
  logo: prismicT.ImageField<never>;
}
/**
 * Default variation for Sponsors Slice
 *
 * - **API ID**: `default`
 * - **Description**: `Sponsors`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type SponsorsSliceDefault = prismicT.SharedSliceVariation<
  "default",
  Simplify<SponsorsSliceDefaultPrimary>,
  Simplify<SponsorsSliceDefaultItem>
>;
/**
 * Slice variation for *Sponsors*
 *
 */
type SponsorsSliceVariation = SponsorsSliceDefault;
/**
 * Sponsors Shared Slice
 *
 * - **API ID**: `sponsors`
 * - **Description**: `Sponsors`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type SponsorsSlice = prismicT.SharedSlice<
  "sponsors",
  SponsorsSliceVariation
>;
/**
 * Primary content in TextHeader → Primary
 *
 */
interface TextHeaderSliceDefaultPrimary {
  /**
   * Publish field in *TextHeader → Primary*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: text_header.primary.hide
   * - **Documentation**: https://prismic.io/docs/core-concepts/boolean
   *
   */
  hide: prismicT.BooleanField;
  /**
   * Header field in *TextHeader → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: text_header.primary.header
   * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
   *
   */
  header: prismicT.KeyTextField;
}
/**
 * Default variation for TextHeader Slice
 *
 * - **API ID**: `default`
 * - **Description**: `Default`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type TextHeaderSliceDefault = prismicT.SharedSliceVariation<
  "default",
  Simplify<TextHeaderSliceDefaultPrimary>,
  never
>;
/**
 * Slice variation for *TextHeader*
 *
 */
type TextHeaderSliceVariation = TextHeaderSliceDefault;
/**
 * TextHeader Shared Slice
 *
 * - **API ID**: `text_header`
 * - **Description**: `TextHeader`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type TextHeaderSlice = prismicT.SharedSlice<
  "text_header",
  TextHeaderSliceVariation
>;
declare module "@prismicio/client" {
  interface CreateClient {
    (
      repositoryNameOrEndpoint: string,
      options?: prismic.ClientConfig
    ): prismic.Client<AllDocumentTypes>;
  }
  namespace Content {
    export type {
      EventDocumentData,
      EventDocumentDataSlicesSlice,
      EventDocument,
      NavigationDocumentData,
      NavigationDocumentDataLinksItem,
      NavigationDocumentDataSlicesSlice,
      NavigationDocument,
      PageDocumentData,
      PageDocumentDataSlicesSlice,
      PageDocument,
      AllDocumentTypes,
      CarouselSliceDefaultPrimary,
      CarouselSliceDefaultItem,
      CarouselSliceDefault,
      CarouselSliceVariation,
      CarouselSlice,
      ContentSliceDefaultPrimary,
      ContentSliceDefaultItem,
      ContentSliceDefault,
      ContentSliceVariation,
      ContentSlice,
      EventsSliceDefaultPrimary,
      EventsSliceDefaultItem,
      EventsSliceDefault,
      EventsSliceVariation,
      EventsSlice,
      FormSliceDefaultPrimary,
      FormSliceDefault,
      FormSliceVariation,
      FormSlice,
      GallerySliceDefaultPrimary,
      GallerySliceDefaultItem,
      GallerySliceDefault,
      GallerySliceVariation,
      GallerySlice,
      PageHeaderSliceDefaultPrimary,
      PageHeaderSliceDefault,
      PageHeaderSliceVariation,
      PageHeaderSlice,
      SponsorsSliceDefaultPrimary,
      SponsorsSliceDefaultItem,
      SponsorsSliceDefault,
      SponsorsSliceVariation,
      SponsorsSlice,
      TextHeaderSliceDefaultPrimary,
      TextHeaderSliceDefault,
      TextHeaderSliceVariation,
      TextHeaderSlice,
    };
  }
}
