// Code generated by Slice Machine. DO NOT EDIT.

import Carousel from './Carousel';
import Events from './Events';
import Form from './Form';
import Gallery from './Gallery';
import PageHeader from './PageHeader';
import Sponsors from './Sponsors';
import TextHeader from './TextHeader';

export {
	Carousel,
	Events,
	Form,
	Gallery,
	PageHeader,
	Sponsors,
	TextHeader
};

export const components = {
	carousel: Carousel,
	events: Events,
	form: Form,
	gallery: Gallery,
	page_header:PageHeader,
	sponsors: Sponsors,
	text_header:TextHeader
};
