// Code generated by Slice Machine. DO NOT EDIT.

import { defineAsyncComponent } from "vue";
import { defineSliceZoneComponents } from "@prismicio/vue";

export const components = defineSliceZoneComponents({
  events: defineAsyncComponent(() => import("./Events/index.vue")),
  headline: defineAsyncComponent(() => import("./Headline/index.vue")),
  media: defineAsyncComponent(() => import("./Media/index.vue")),
  paragraph: defineAsyncComponent(() => import("./Paragraph/index.vue")),
  section: defineAsyncComponent(() => import("./Section/index.vue")),
  slider: defineAsyncComponent(() => import("./Slider/index.vue")),
});
