// Code generated by Slice Machine. DO NOT EDIT.

import Carousel from './Carousel';
import Events from './Events';
import Sponsors from './Sponsors';
import PageHeader from './PageHeader';
import Gallery from './Gallery';
import TextHeader from './TextHeader';

export {
	Carousel,
	Events,
	Sponsors,
	PageHeader,
	Gallery,
	TextHeader
};

export const components = {
	carousel: Carousel,
	events: Events,
	sponsors: Sponsors,
	page_header:PageHeader,
	gallery: Gallery,
	text_header:TextHeader
};
