// Code generated by Slice Machine. DO NOT EDIT.

import { defineAsyncComponent } from "vue";
import { defineSliceZoneComponents } from "@prismicio/vue";

export const components = defineSliceZoneComponents({
  carousel: defineAsyncComponent(() => import("./Carousel/index.vue")),
  events: defineAsyncComponent(() => import("./Events/index.vue")),
  gallery: defineAsyncComponent(() => import("./Gallery/index.vue")),
  page_header: defineAsyncComponent(() => import("./PageHeader/index.vue")),
  sponsors: defineAsyncComponent(() => import("./Sponsors/index.vue")),
});
